### ISSUE TITLE
action=backup does not backup all language variants and therefore cannot restore!

### ISSUE THREAD

**Issue by owain68** [Kentico/kontent-backup-manager-js#11]
### Brief bug description

When I look at the contents languageVariants.json I am missing LVs for content items in contentItems.json. I have 82 content_items of a content_type but only 58 language_variants are exported.  When I query management API for a missing language item it appears in the response as expected

### Repro steps

1. `kbm action=backup`
2. unzip file
3. see that there are missing language variants
4. `kbm action=restore` into an empty project fails

### Expected behaviour

All language variants are exported and the restore will load them all.

### Test environment

 - Platform/OS: MacOS/iTerm2
 - Browser iTerm2
 - Version no idea
 - Script for cross-referencing 
`const jp = require('jsonpath')   //test with https://jsonpath.com/

// const backupDirectory = '../../data/kontent-backup-7-12-2020-13-5'
const backupDirectory = '../../data/kontent-backup-11-12-2020-9-53'

const contentItems = require(backupDirectory + '/contentItems.json')
const languageVariants = require(backupDirectory + '/languageVariants.json')
const contentTypes = require(backupDirectory + '/contentTypes.json')

const cmpContentTypeId = jp.query(contentTypes, '$[?(@.codename=="cmp")].id')[0]
console.log('CMP Content Type id:', cmpContentTypeId)
const cmpIdElementId = jp.query(contentTypes, '$[?(@.codename=="cmp")].elements[?(@.codename=="wgv_cmp_id")].id')[0]

console.log('wgv_cmp_id element id:', cmpIdElementId)

const contentItemsCmp = jp.query(contentItems, `$[?(@.type.id==\'${cmpContentTypeId}\')].id`)
console.log('Number of CMP content_items:', contentItemsCmp.length)

let ci2Cmp = new Map()
console.log('Language variant count: ', languageVariants.length)
contentItemsCmp.forEach(ci => {
  const cmpId = jp.query(languageVariants, `$[?(@.item.id=='${ci}')].elements[?(@.element.id=='${cmpIdElementId}')].value`)[0]
  ci2Cmp.set(ci,cmpId)
})
console.table(ci2Cmp)`

### Additional context

There is a long discussion on Intercom with Daniel.  The `action=restore` fails like this.  Is it two issues or the same one?

`Imported: arts___culture (default) | languageVariant
Attempt 1: retrying in 2126ms
Attempt 2: retrying in 2367ms
Attempt 3: retrying in 5470ms
ContentManagementBaseKontentError {
  validationErrors: [
    ValidationError {
      message: "The requested modular content item 'd1b68bc3-0cb4-477f-b88e-8bd625c8b1bc' for the element 'tags' was not found."
    }
  ],
  message: "The provided request body is invalid. See 'validation_errors' for more information and specify a valid JSON object.",
  requestId: '50e370dea98d6e45',
  errorCode: 5,
  originalError: Error: Request failed with status code 400
      at createError (/Users/owain/dev/wg-content-load/node_modules/@kentico/kontent-backup-manager/node_modules/axios/lib/core/createError.js:16:15)
      at settle (/Users/owain/dev/wg-content-load/node_modules/@kentico/kontent-backup-manager/node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (/Users/owain/dev/wg-content-load/node_modules/@kentico/kontent-backup-manager/node_modules/axios/lib/adapters/http.js:236:11)
      at IncomingMessage.emit (events.js:327:22)
      at endReadableNT (_stream_readable.js:1224:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21) {
    config: {
      url: 'https://manage.kontent.ai/v2/projects/b198ddf3-8449-01e5-ab71-46c587c525c0/items/codename/cancer_research_uknnnnnnn/variants/codename/default',
      method: 'put',
      data: '{"elements":[{"element":{"codename":"manual"},"value":[{"codename":"true"}]},{"element":{"codename":"full_name"},"value":"Cancer Research UK"},{"components":[],"element":{"codename":"description"},"value":"<p>Cancer Research UK is a cancer research and awareness charity in the United Kingdom and Isle of Man, formed on 4 February 2002 by the merger of The Cancer Research Campaign and the Imperial Cancer Research Fund. Its aim is to reduce the number of deaths from cancer.</p>"},{"element":{"codename":"address"},"value":"2 Redman Place, London"},{"element":{"codename":"postcode"},"value":"E20 1JQ"},{"element":{"codename":"charity_registration_id"},"value":"CCEW-1089464"},{"element":{"codename":"gift_aid_eligible"},"value":[{"codename":"true"}]},{"element":{"codename":"payroll_giving_eligible"},"value":[{"codename":"true"}]},{"element":{"codename":"logo"},"value":[{"id":"c41a30a8-9003-4cc3-825a-3025f4ebccbd"}]},{"element":{"codename":"hero_image"},"value":[{"id":"1a269cf2-f6b8-4221-afe8-de2b49cba8e9"}]},{"element":{"codename":"withdrawn_on"},"value":null},{"element":{"codename":"website"},"value":""},{"element":{"codename":"youtube"},"value":""},{"element":{"codename":"twitter"},"value":""},{"element":{"codename":"facebook"},"value":""},{"element":{"codename":"parent_cmp"},"value":[]},{"element":{"codename":"related_cmps"},"value":[]},{"element":{"codename":"tags"},"value":[{"id":"d1b68bc3-0cb4-477f-b88e-8bd625c8b1bc"},{"codename":"health"}]},{"element":{"codename":"wgv_cmp_id"},"value":"CMP#GB1#WGV#84f69713-77ff-46d1-8fe7-44f0ab77a61a"},{"element":{"codename":"default_asset_folder_id"},"value":"97554d98-aa0f-46e6-ad41-84767dc7c11d"},{"element":{"codename":"ctid"},"value":"1089464"},{"element":{"codename":"ccew"},"value":""},{"element":{"codename":"ccsc"},"value":""},{"element":{"codename":"ccni"},"value":""},{"element":{"codename":"ct"},"value":""},{"element":{"codename":"md"},"value":""},{"element":{"codename":"jgos"},"value":""},{"element":{"codename":"jggc"},"value":""}]}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: 'Infinity',
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'PUT /v2/projects/b198ddf3-8449-01e5-ab71-46c587c525c0/items/codename/cancer_research_uknnnnnnn/variants/codename/default HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'X-KC-SDKID: npmjs.com;@kentico/kontent-management;0.4.2\r\n' +
        'authorization: bearer ew0KICAiYWxnIjogIkhTMjU2IiwNCiAgInR5cCI6ICJKV1QiDQp9.ew0KICAianRpIjogImQ3MmVmZDYwYjAxMTQzNTlhNTAyZGZhNjkwMTA4NDFkIiwNCiAgImlhdCI6ICIxNjA3Njg4Njc3IiwNCiAgImV4cCI6ICIxOTUzMjg4Njc3IiwNCiAgInByb2plY3RfaWQiOiAiYjE5OGRkZjM4NDQ5MDFlNWFiNzE0NmM1ODdjNTI1YzAiLA0KICAidmVyIjogIjIuMS4wIiwNCiAgInVpZCI6ICI1ZDcyMjViM2FlNzAwMjBkZjZiNmQyYmEiLA0KICAiYXVkIjogIm1hbmFnZS5rZW50aWNvY2xvdWQuY29tIg0KfQ.gbUeRJOi7hueIr17VlUdqYBoJEWaAd6LnKTzePWvaSQ\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 2007\r\n' +
        'Host: manage.kontent.ai\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'PUT',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v2/projects/b198ddf3-8449-01e5-ab71-46c587c525c0/items/codename/cancer_research_uknnnnnnn/variants/codename/default',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    response: {
      status: 400,
      statusText: 'Bad Request',
      headers: [Object],
      config: [Object],
      request: [ClientRequest],
      data: [Object]
    },
    isAxiosError: true,
    toJSON: [Function (anonymous)]
  }
}
Management API error occured: The provided request body is invalid. See 'validation_errors' for more information and specify a valid JSON object.
The requested modular content item 'd1b68bc3-0cb4-477f-b88e-8bd625c8b1bc' for the element 'tags' was not found.`

### Screenshots

Add links to screenshots, if possible.
contentItems.json
`{
    "id": "a4edde85-aa34-483c-89cd-776be144aa00",
    "name": "XXXXX",
    "codename": "XXXX",
    "type": { "id": "5239fbf7-4cb6-4100-bc4b-1452c172ee10" },
    "collection": { "id": "00000000-0000-0000-0000-000000000000" },
    "sitemap_locations": [],
    "last_modified": "2020-08-26T15:30:39.9274371Z"
  }`

![languageVariants.json](https://user-images.githubusercontent.com/191453/101907335-50c16080-3bb2-11eb-8640-2a536040ec45.png)

**Comment by Enngage** [comment]
Hey,

What version of kontent-backup-manager are you using? There was an issue in previous versions which didn't use pager correctly and so not all data were loaded. This should however not be an issue with latest version, can you update and makre sure you are using the latest version?

As for the validation errors - in the exported zip file there is a "validation.json" which contains possible inconsistencies in project data. To successfully restore it, you have to fix these issues first.

**Comment by owain68** [comment]
`➜  data git:(ccat) ✗ kbm --version                                                                                                                                                           1.12.0`

I do have one validation error in `validation.json` and I can see the message now when I look.  

Project contains inconsistencies which may cause future import to not work.

Indeed there is one item_variant with an issue.  I will fix that and retry.  It might be getting to that one and ignoring the rest?

**Comment by Enngage** [comment]
The fix for pager was fixed in `1.7.0` so I think you should update :-) https://github.com/Kentico/kontent-backup-manager-js/blob/master/CHANGELOG.md#bug-fixes-3

That is very much possible - if the request fails, the program ends.

**Comment by owain68** [comment]
I am running 1.12.0

`➜  data git:(ccat) ✗ kbm --version
1.12.0`

I have cleaned up two validation issues and the backup completes without any errors and with

validation.json

`{
  "project": {
    "id": "xxx-xxx-xxx-xxxx-xxxx",
    "name": "Catalogue",
    "environment": "Production"
  },
  "variant_issues": [],
  "type_issues": []
}
`
When I run my script again to cross reference content_items of a particular type, I still only get 58 language variants out of a possible 81.

`/Users/owain/.nvm/versions/node/v14.3.0/bin/node /Users/owain/dev/wg-content-load/src/kontent-ai/hackBackupExternalIdtoCampaignId.js
CMP Content Type id: 5239fbf7-4cb6-4100-bc4b-1452c172ee10
wgv_cmp_id element id: 6d40fe33-7495-41fc-a6e0-63bbf6033713
Number of CMP content_items: 81
Language variant count:  58
┌───────────────────┬────────────────────────────────────────┬────────────────────────────────────────────────────┐
│ (iteration index) │                  Key                   │                       Values                       │
├───────────────────┼────────────────────────────────────────┼────────────────────────────────────────────────────┤
│         0         │ 'e2c37637-1652-4eee-9e2d-5187fc16a35e' │ 'CMP#GB1#WGV#84f69713-77ff-46d1-8fe7-44f0ab77a61a' │
│         1         │ 'f9e601f1-c66e-4860-a221-fbbfce2d6a4b' │ 'CMP#GB1#WGV#cda7c9a9-8167-4020-be24-82847801be71' │
│         2         │ 'b58d96c8-9e0d-4adb-a570-b7af1ad7635f' │ 'CMP#GB1#WGV#b7cd0197-da7a-4c2d-8692-3fdde5a04c4e' │
│         3         │ '890817f7-da27-4a15-a2be-04638d708310' │ 'CMP#GB1#WGV#a25a45b2-e376-4331-8e72-01d02f427896' │
│         4         │ 'f28d7476-51c4-43ae-b815-b5bb2493f729' │ 'CMP#GB1#WGV#c9f30b77-f580-475e-b20f-a32e27e24a6b' │
│         5         │ 'cf39d217-8170-427d-b948-9a8759d151f4' │ 'CMP#GB1#WGV#c633e8ba-2042-4c06-9db6-a3e5f9324105' │
│         6         │ '8f86e40d-21ed-4b8f-b329-d75edb419f81' │ 'CMP#GB1#WGV#79a9b6d8-9fb0-439e-b769-3a081b673552' │
│         7         │ '9743834a-d8f7-4524-8dad-f8679fb89dca' │ 'CMP#GB1#WGV#9b191648-ccaa-43f4-965f-137d1b4caf70' │
│         8         │ 'cb26077a-af88-4d35-9396-1772a6dfff66' │ 'CMP#GB1#WGV#adafe852-536e-4c45-87e9-4754adf2a922' │
│         9         │ '7b856d24-04c6-4a35-8d57-3991ebf71a00' │ 'CMP#GB1#WGV#a0d71c47-d41e-4e2e-a582-d0da33f9a233' │
│        10         │ '9a011d8a-ec6d-4847-9b9b-df86e807c0fe' │ 'CMP#GB1#WGV#11465fc3-3e33-4de9-985d-01681499fd55' │
│        11         │ '07d342ec-a57d-4eff-b350-f36528065a02' │ 'CMP#GB1#WGV#a5e66f24-191e-45e2-81b9-e3ec04591105' │
│        12         │ '2f18c910-3577-425b-80ba-2ad50315b45c' │ 'CMP#GB1#WGV#dcfaec0c-5da4-4621-87a5-684c18e975d7' │
│        13         │ 'e2b49f58-e1aa-4d41-bfba-167feef1ba03' │ 'CMP#GB1#WGV#a6a4dddd-58aa-44f5-9271-cfebadae494c' │
│        14         │ '40c1efe9-22e5-4e69-8e06-a66a9aa31c94' │ 'CMP#GB1#WGV#99aaffc6-702e-4585-9468-aeccdcf1536b' │
│        15         │ '219465ce-f6b0-4b0a-a1a0-0adb2041ac8e' │ 'CMP#GB1#WGV#e6b053fc-cc5b-4b6c-9ed8-413a010fe26a' │
│        16         │ '2d57828c-5f91-49d7-83d9-5cb9ae6368cb' │ 'CMP#GB1#WGV#105bc450-ffba-44f4-be16-b3320034d8da' │
│        17         │ '77569f79-0977-4de7-b28b-cca40fbbc418' │ 'CMP#GB1#WGV#da2c9819-5e4c-4c91-80e3-31e2a61b178a' │
│        18         │ 'fb15383f-f98b-49aa-a9f3-94c2d35decc2' │ 'CMP#GB1#WGV#07998adb-dbf0-449e-9629-78e45ac325d6' │
│        19         │ 'd27e05ed-0302-4f1d-8903-19b0aa269b03' │ 'CMP#GB1#WGV#20f604bd-c247-454b-84f2-4ee662a350fb' │
│        20         │ '32e0d1ed-8132-4f7d-9e9e-3160d7f2e83b' │ 'CMP#GB1#WGV#73f2dde2-7e09-4b96-bb14-1f1eeed8c3c0' │
│        21         │ 'c7d9cd2f-bc1b-4bed-9208-69fbc6a704a9' │ 'CMP#GB1#WGV#dd8a3570-c975-430b-b69c-59fd46b7776c' │
│        22         │ 'b8b87359-0de5-4835-92fa-036f0a1b9a22' │ 'CMP#GB1#WGV#ea2edeb4-fcf2-4003-9b38-600c33a2566c' │
│        23         │ '8eab8468-ca61-405d-a12a-7350bc1c0bd9' │ 'CMP#GB1#WGV#f4588808-861d-47f4-80a1-58c6295a72d4' │
│        24         │ '5c95628f-20de-48da-8d45-a145f3bc44d9' │ 'CMP#GB1#WGV#8720a2d5-fd82-44f3-a7b4-f1e0b951d77a' │
│        25         │ '89314f07-2281-44b8-93a6-31f36ddf0dbe' │ 'CMP#GB1#WGV#2ca737fb-c0eb-4d8d-8371-caa1c86d9d43' │
│        26         │ 'c8b0866b-d0ce-4a48-b29e-13491b423c70' │ 'CMP#GB1#WGV#3b198ef8-389c-4e7f-9bee-9ac457fbd17a' │
│        27         │ '3ab5fe1e-76c4-4cfb-8413-c74a57edeabf' │ 'CMP#GB1#WGV#906dd22d-2ed6-4ec6-9be4-3e66cdb6a745' │
│        28         │ '2071055e-c2d8-46e8-9438-3166dfc19eb4' │ 'CMP#GB1#WGV#1273f0f1-f94c-4973-b312-bad29a724711' │
│        29         │ '075a6dc7-00c2-4ef8-92f4-d7338acad943' │ 'CMP#GB1#WGV#dfe7736a-8cd1-47ba-807d-e023237e727f' │
│        30         │ '0391543f-c636-49c4-b5f4-049f7280e6c0' │ 'CMP#GB1#WGV#00049bb0-be0f-460e-91d5-6f01aa0dd10f' │
│        31         │ '633fdf53-815c-449f-8b53-c051a90d2388' │ 'CMP#GB1#WGV#97e780c5-d949-4a06-9737-8a022157d012' │
│        32         │ 'd7d9dfe7-17c9-4ec5-a541-1b86698684d9' │ 'CMP#GB1#WGV#8c950157-8ea6-46eb-87b7-ddd234b0e71a' │
│        33         │ '221b537d-4f23-49c6-a326-0be54d655abd' │ 'CMP#GB1#WGV#dccd641a-9d70-4d3e-b833-ae10901f69ff' │
│        34         │ 'be6a03dc-b941-4bbe-9281-4bf50cd8f6f2' │ 'CMP#GB1#WGV#acd9a549-5dbc-401b-8365-932a514bbc57' │
│        35         │ 'a14aea69-72fe-4b91-9ffc-fcec30001cce' │ 'CMP#GB1#WGV#ae5d287a-5ed0-4385-b245-0c6ba8d428f1' │
│        36         │ '360f2e33-d03e-48ad-bd5e-9d7073af163a' │ 'CMP#GB1#WGV#5719e01d-1987-4149-aa90-6207e4219e72' │
│        37         │ 'a1297e90-f8ea-4b2f-9dfe-59be0db39c17' │ 'CMP#GB1#WGV#16b4171f-0c09-4c52-82d5-04a09f85ac55' │
│        38         │ '39cb36a3-b99f-4f83-936a-1a52b92166f6' │ 'CMP#GB1#WGV#0c92fd4b-7c42-4269-8001-5fb3fa6ded7d' │
│        39         │ 'ce17080c-cbeb-4b0c-a9b2-5cc9cc9f61e0' │ 'CMP#GB1#WGV#89add0b2-b856-4bda-8018-a3dcf7d8975f' │
│        40         │ 'abd1a0e0-4185-4f9e-b04c-e5897ed08fbb' │ 'CMP#GB1#WGV#4f4269d4-422c-4750-be4e-f35e0d48bc36' │
│        41         │ '0056ef35-9c0f-4db5-b61a-0703e44de76c' │ 'CMP#GB1#WGV#0f58bed7-1a09-49b7-a524-32f573b23d7d' │
│        42         │ '2fc8f5b7-1d30-4de1-9e40-a2a451237d35' │ 'CMP#GB1#WGV#f2a9d11e-a4fe-4eed-82c7-65b1cd31579c' │
│        43         │ '987f036f-99d8-4893-9f3b-06da2c993a6f' │ 'CMP#GB1#WGV#2c7f218c-5498-487b-8a80-14b729b85612' │
│        44         │ 'e6d0ca3b-781c-4697-a8d3-9b4f0c1ee60d' │ 'CMP#GB1#WGV#9d0a528f-1292-43f9-ac2b-8c6e625c8953' │
│        45         │ 'fdb14980-0610-4164-9977-daf7938235bf' │ 'CMP#GB1#WGV#da0019e6-b8f9-43e8-9541-1448729b3eee' │
│        46         │ '9f095ec7-de9f-4346-8a14-aa20d02fff44' │ 'CMP#GB1#WGV#add533da-6839-4cbf-953a-8f15a38ff27f' │
│        47         │ 'dca5f9e6-1c9c-42ac-b24b-e021aecea155' │ 'CMP#GB1#WGV#63a3e341-bdfe-4c87-8d1e-337b2a89f78c' │
│        48         │ '3e194a27-0f27-4863-902c-4e8afe3a0f28' │ 'CMP#GB1#WGV#85d6f592-5978-4178-8845-7caab3b388b4' │
│        49         │ '35b01cff-4847-45ed-bee0-d4fc93f33f3e' │ 'CMP#GB1#WGV#c637fe7b-598c-4f6d-a80b-31280b79e261' │
│        50         │ '9963356d-8e09-4d41-9231-5645aecc9569' │                     undefined                      │
│        51         │ 'a0a6341c-aeef-47a2-afe8-eebbb7de0fec' │                     undefined                      │
│        52         │ '6bba2b40-2819-4945-bf4f-3d32cc86bcac' │                     undefined                      │
│        53         │ '8ad8dfdb-e040-44d2-b21a-3d828dba4ace' │                     undefined                      │
│        54         │ '6946efde-f81f-4c23-9510-0ebee9e3e210' │                     undefined                      │
│        55         │ '6a11a519-02bf-4fe0-992d-1c705d6f3282' │                     undefined                      │
│        56         │ '7d2588e6-f5ca-465d-99a7-0936f1226347' │                     undefined                      │
│        57         │ 'ccbf9ccc-9f96-4695-bdef-3f06b15f3fd5' │                     undefined                      │
│        58         │ '94f13e33-cf84-4e8a-8cae-c2971b06e909' │                     undefined                      │
│        59         │ '3dd2ecfa-db68-4650-ae55-1af3b472908f' │                     undefined                      │
│        60         │ '4cf544c4-bd80-4323-b11a-5894808a9840' │                     undefined                      │
│        61         │ 'a554cd98-1b58-4416-aac4-88b0663a1b93' │                     undefined                      │
│        62         │ 'e81aa409-8665-4f14-bb04-2091b372cfd5' │                     undefined                      │
│        63         │ 'a862c19f-81eb-4a47-b0de-5c967b0a5b35' │                     undefined                      │
│        64         │ 'a4edde85-aa34-483c-89cd-776be144aa00' │                     undefined                      │
│        65         │ '9a5f59e8-6fce-448d-954a-0fe11e8dd5a6' │                     undefined                      │
│        66         │ '9ae832e1-c4f0-4874-9d5f-7bba2e7807d9' │                     undefined                      │
│        67         │ 'eed1aea8-c8db-46d3-a355-77e2628d6dcc' │                     undefined                      │
│        68         │ '19be01ad-5af0-467f-bb56-650ed3d13aa0' │                     undefined                      │
│        69         │ 'ea7d582d-e96f-4670-9216-5a921635a31f' │                     undefined                      │
│        70         │ '26b1766c-d15d-4122-8115-db6c54609d17' │                     undefined                      │
│        71         │ '5f3ef235-123f-4a0c-93de-6e79b6d866c6' │                     undefined                      │
│        72         │ '5b91ae6b-854c-4250-9689-38342e401744' │                     undefined                      │
│        73         │ '8c840f9c-07d6-43e8-ba23-f206130903ce' │                     undefined                      │
│        74         │ 'c4c3ba93-5c75-4ea2-a889-11d1ec295ef1' │                     undefined                      │
│        75         │ 'c1ab0ab7-4d19-4691-a688-d3dff890aec7' │                     undefined                      │
│        76         │ '2ac2d533-c01b-4eb1-8e29-d229625980fd' │                     undefined                      │
│        77         │ '2ec801d8-8882-425b-98e7-af1beba77e6e' │                     undefined                      │
│        78         │ '642ed6b7-abf6-415d-85b2-d4f7a0cb129d' │                     undefined                      │
│        79         │ '9e3da72f-5551-4c35-bf4b-e64d1b6c4a66' │                     undefined                      │
│        80         │ '6d7e3706-a6e2-5972-927f-1820636caff5' │                     undefined                      │
└───────────────────┴────────────────────────────────────────┴────────────────────────────────────────────────────┘

Process finished with exit code 0
`

Seems strange it stops after 58 language variants.  I guess all I can do is rather than run it from the command line I run it from node and go through a whole debugging exercise.  

Maybe the 59th one is crashing out to possibly hit rate limiting issues?

**Comment by owain68** [comment]
<img width="572" alt="SS1040" src="https://user-images.githubusercontent.com/191453/101984549-04d9ee80-3c7a-11eb-8eb7-325709cf29dc.png">

This running the export service directly in code.  Am I correct in thinking that every content item must have at least one language variant?

**Comment by owain68** [comment]
@Enngage Richard I now suspect that this is a pagination issue - I only get page 1 of Language variants.  

I am by no means a JS/TS developer but I cannot see where token is being set for the second page at https://github.com/Kentico/kontent-backup-manager-js/blob/master/src/export/export.service.ts#L170 and also https://github.com/Kentico/kontent-backup-manager-js/blob/master/src/export/export.service.ts#L183. I can see that token would be null on the first invocation but I cannot see where the second invocation happens and how it receives the token. It may be wrapped up in `withListQueryConfig` somewhere?

Thanks.

**Comment by Enngage** [comment]
Hey @owain68 , a content item`can have `0-n` language variants, so it is perfectly valid to have different number of language variants to content items (that is because content item does not have to be localized to all available languages). 

The 'fetch all with paging' functionality is actually provided by the CM SDK by using the `toAllPromise` (see https://github.com/Kentico/kontent-backup-manager-js/blob/master/src/export/export.service.ts#L193)

Can you verify the number of language variants of the content item you are testing?

**Comment by owain68** [comment]
`  await client.listLanguageVariantsOfContentType()
    // .listLanguageVariantsOfContentTypeWithComponents()
    .byTypeId('codename/cmp')
    .toAllObservable()
    .subscribe((response) => {
      console.log(JSON.stringify(response.data, null, 2))
      console.log('Language Variant count:', response.data.items.length)

    })` 

`Language Variant count: 81`

@Enngage

**Comment by Enngage** [comment]
Well, you have to compare this to the actual data in your project. I'm not able to verify if this is or isnt correct ;-)

**Comment by owain68** [comment]
![From console](https://user-images.githubusercontent.com/191453/102106289-49a38800-3e28-11eb-846b-3fac6ca2eba1.png)

@Enngage ;-). Also the support ticket raised can confirm there are LVs missing.  Woud you like some keys to "have a play"?

**Comment by Enngage** [comment]
@owain68 thats not exactly what I meant. You are saying that the export zip package does not contain all language variants for content items. What you need to do is take a look at one specific content item in the zip package (the one you say does not have all language variants in export) and take a note of its id / codename. Then take a look at the languageVariants (again in the zip) having the content item and see how many language variants there are.

Once you know that, make a GET request for that content item and get a note of the language variants (https://docs.kontent.ai/reference/management-api-v2#operation/retrieve-language-variants-of-an-item). Once you have this information, you can see whether the count matches the export or not.

**Comment by owain68** [comment]
@Enngage I gave support the curl request generated by Postman.

Here goes.

Iteration 50 from [above](https://github.com/Kentico/kontent-backup-manager-js/issues/11#issuecomment-743339278)

zipfile/contentItems.json
```
{
    "id": "9963356d-8e09-4d41-9231-5645aecc9569",
    "name": "Xcannappeal",
    "codename": "xcannappeal",
    "type": { "id": "5239fbf7-4cb6-4100-bc4b-1452c172ee10" },
    "collection": { "id": "00000000-0000-0000-0000-000000000000" },
    "sitemap_locations": [],
    "last_modified": "2020-07-16T16:01:48.3063478Z"
  }
``` 
```
grep -n '9963356d-8e09-4d41-9231-5645aecc9569' languageVariants.json | wc -l 
 0
```
therefore no lines in the languageVariants.json file with the id of the content_item being investigated.

When I execute the API call via curl:

```
curl --location --request GET 'https://manage.kontent.ai/v2/projects/yyyyyyyyyy/items/9963356d-8e09-4d41-9231-5645aecc9569/variants' \
--header 'Authorization: Bearer xxxxxxxxxxxxxx' | | grep 9963356d-8e09-4d41-9231-5645aecc9569 | wc -l
1
```
which shows that the management API is seeing **one** language variant for this content item.  You can see from the original post that there are index lines 50-80 (content_item id) which leads me to suspect pagination is not working or something returned in the payload is causing a failure.

**Comment by owain68** [comment]
@Enngage let me know if you would like to see for yourself.  I can give you a MAPI key fofromr our staging environment.  I have tried the export from this environment, more out of desperation, and it still only extracts 58 language variants.

```
{
  "assetFoldersCount": 84,
  "assetsCount": 275,
  "contentItemsCount": 89,
  "contentTypeSnippetsCount": 0,
  "contentTypesCount": 2,
  "languageVariantsCount": 58,
  "languagesCount": 1,
  "taxonomiesCount": 1
}
```

**Comment by Enngage** [comment]
@owain68 I've verified that paging is working correctly on a large project, but for some reason I had some language variants missing too. I have no idea why, but I suspect this is something to do with the actual endpoints. 

I've changed the endpoint that loads language variants and it actually helped and I was able to get all variants in my project. This endpoint is however a bit slower because it creates 1 request per 1 content item. We will probably have to investigate why the other endpoint don't return all variants. 

For now, can you update this library to version `1.13.0` and see if you get all the items?

**Comment by owain68** [comment]
@Enngage I am now getting the correct number of variants using `1.13.0`, and indeed, it is slower.  Might it be a rate-limiting issue? 

Thanks for your help with this.

**Comment by Enngage** [comment]
@owain68 Rate limiting is not an issue here - its the number of request that are needed to get all data. As I mentioned in previous message, I have to make 1 request for language variants for 1 content item. Previously, I was using listing query to get language variants that supports paging, but doesn't for some reason get all variants.

**Comment by owain68** [comment]
@Enngage Richard, thanks for looking into and fixing this in `1.13.0`.  Although it is much slower at least we get all the data.  I will let you decide whether you want to close this issue or keep it open do determine whether there is an issue with the sdk  for `listLanguageVariantsOfContentTypeWithComponents` and/or `listLanguageVariantsOfContentType` . 

https://github.com/Kentico/kontent-backup-manager-js/commit/6bdda7d5b7aaf73103f46ade0a6a14e31b9ece30
