### ISSUE TITLE
Zipfile service has no axios retry logic

### ISSUE THREAD

**Issue by owain68** [Kentico/kontent-backup-manager-js#18]
### Motivation

On exporting large number of assets to binary files I have had to perform a number of re-runs due to node throwing the axios exception `ECONNRESET` when retrieving from the CDN(!!)

### Proposed solution

It would be pertinent to have axios perform some sort of retry logic in the code before throwing an exception.  Perhaps this could be made configurable.

### Additional context

https://github.com/Kentico/kontent-backup-manager-js/blob/eb532298c10991276ab0464842b32315803eb4eb/lib/zip/zip.service.ts#L196

**Comment by Enngage** [comment]
Implemented in `2.0.0-next.1`
