### ISSUE TITLE
Request to add proxy support

### ISSUE THREAD

**Issue by alexaustrade** [Kentico/kontent-backup-manager-js#7]
### Motivation

Add proxy support to Export/Import Service so Backup Manager can be used on a corporate network behind a proxy server.

### Proposed solution

Expose optional proxy config via IExport/Import Config?

### Additional context

See support case with andrewh from 29/07/2020

**Comment by Enngage** [comment]
Hi @alexaustrade,

This is already supported with the use of `baseUrl` that you can specify when exporting / importing (e.g. see https://github.com/Kentico/kontent-backup-manager-js/blob/master/src/export/export.service.ts#L26).

CLI also exposes `baseUrl` that you can set up in CMD - https://github.com/Kentico/kontent-backup-manager-js#configuration

**Comment by alexaustrade** [comment]
Thanks @Enngage I ran the follow:

kbm --action=backup --apiKey='api-key-here' --projectId='project-id-here' --zipFilename='output-path-here' --baseUrl='http://127.0.0.1:8080'

And I can see the request URL changes from: https://manage.kontent.ai/v2/projects/project-id-here/validate to: http://127.0.0.1:8080/project-id-here/validate

I assume this will let me direct the web request to an endpoint that has proxy support and then I can rewrite the the web request?

**Comment by Enngage** [comment]
Yeah, you can change it to any URL you want ;)
